- name: Setup php.ini
  copy:
    src: php_{{ php_version }}.ini
    backup: yes
    dest: "/etc/php.ini"
    group: root
    owner: root
    mode: 0644
  become: yes
  when: custom_phpfpm_ini is not defined

- name: Setup /etc/php-fpm.d/www.conf
  template:
    src: "{{ ansible_distribution }}_www.conf"
    backup: yes
    dest: "/etc/php-fpm.d/www.conf"
    group: root
    owner: root
    mode: 0644
  become: yes
  when: custom_phpfpm_www_conf is not defined

- name: Setup custom php.ini (php-fpm)
  copy:
    src: "{{ custom_phpfpm_ini }}"
    backup: yes
    dest: "/etc/php.ini"
    group: root
    owner: root
    mode: 0644
  when: custom_phpfpm_ini is defined

- name: Setup php-fpm (pool.d/www.conf)
  copy:
    src: "{{ custom_phpfpm_www_conf }}"
    backup: yes
    dest: "/etc/php-fpm.d/www.conf"
    group: root
    owner: root
    mode: 0644
  when: custom_phpfpm_www_conf is defined
