- name: Setup php{{ php_version }}-fpm | /etc/php/{{ php_version }}/fpm/php.ini
  copy:
    src: "{{ php_version }}_php.ini"
    backup: yes
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    group: root
    owner: root
    mode: 0644
  become: yes
  when: custom_phpfpm_ini is not defined

- name: Setup php{{ php_version }}-fpm | /etc/php/{{ php_version }}/fpm/pool.d/www.conf
  template:
    src: "{{ ansible_distribution }}_www.conf"
    backup: yes
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    group: root
    owner: root
    mode: 0644
  become: yes
  when: custom_phpfpm_www_conf is not defined

- name: Setup php{{ php_version }}-fpm | /etc/logrotate.d/php{{ php_version }}-fpm-slow
  template:
    src: Ubuntu/php-fpm-slow
    backup: yes
    dest: "/etc/logrotate.d/php{{ php_version }}-fpm-slow"
    group: root
    owner: root
    mode: 0644
  become: yes

- name: Setup custom php.ini (php-fpm)
  copy:
    src: "{{ custom_phpfpm_ini }}"
    backup: yes
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    group: root
    owner: root
    mode: 0644
  when: custom_phpfpm_ini is defined

- name: Setup php-fpm (pool.d/www.conf)
  copy:
    src: "{{ custom_phpfpm_www_conf }}"
    backup: yes
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    group: root
    owner: root
    mode: 0644
  when: custom_phpfpm_www_conf is defined
